### ISSUE TITLE
ValueError,缺少配置文件。

### ISSUE THREAD

**Issue by DreamLoveBetty** [sdbds/Moore-AnimateAnyone-for-windows#2]
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://3b124d98a8be961bc5.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
D:\Program\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
D:\Program\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py:761: FutureWarning: `torch_dtype` is deprecated and will be removed in version 0.25.0.
  deprecate("torch_dtype", "0.25.0", "")
D:\Program\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Traceback (most recent call last):
  File "D:\Program\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Program\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Program\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Program\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Program\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "D:\Program\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\Program\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Program\Moore-AnimateAnyone-for-windows\app.py", line 69, in animate
    self.denoising_unet = UNet3DConditionModel.from_pretrained_2d(
  File "D:\Program\Moore-AnimateAnyone-for-windows\src\models\unet_3d.py", line 668, in from_pretrained_2d
    motion_state_dict = torch.load(
  File "D:\Program\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\torch\serialization.py", line 808, in load
    raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
_pickle.UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: PytorchStreamReader failed reading file data/17: invalid header or archive is corrupted
---------------------------------------------------------------------------------------------------------------------------------------------------
已将所有权重文件放置“pretrained_weights”目录，还是提示缺少配置文件
![20240116030657](https://github.com/sdbds/Moore-AnimateAnyone-for-windows/assets/138059406/2ec8db81-89e9-4153-8774-97a67d55318b)

**Comment by sdbds** [comment]
应该是某个文件损坏了没下完，看起来是denoising那个。
另外使用自动下载就可以，现在不读取外部VAE，使用sd1-5的
