### ISSUE TITLE
An error occurs when running

### ISSUE THREAD

**Issue by zyjlqx** [sdbds/Moore-AnimateAnyone-for-windows#7]
Traceback (most recent call last):
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\app.py", line 125, in animate
    video = self.pipeline(
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\src\pipelines\pipeline_pose2vid_long.py", line 525, in __call__
    pred = self.denoising_unet(
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\src\models\unet_3d.py", line 493, in forward
    sample, res_samples = downsample_block(
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\src\models\unet_3d_blocks.py", line 441, in forward
    hidden_states = resnet(hidden_states, temb)
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\src\models\resnet.py", line 223, in forward
    hidden_states = self.conv1(hidden_states)
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\src\models\resnet.py", line 14, in forward
    x = super().forward(x)
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\Moore-AnimateAnyone\Moore-AnimateAnyone-for-windows\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by sdbds** [comment]
it seems cuda envirment problem
